name: "Publish: Visual Studio Marketplace"
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - 'package.json'
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PUSH_PAT }}
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install
      - name: Install vsce
        run: npm install -g @vscode/vsce
      - name: Publish
        if: success()
        run: "vsce publish patch -p ${{ secrets.VSCE_PAT }} -m 'build: version bump to %s'"
      - name: Git Push
        run: git push && git push --tags
