on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set git config
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install
      - name: Install vsce
        run: npm install -g @vscode/vsce
      - name: Publish
        if: success()
        run: "vsce publish patch -p ${{ secrets.VSCE_PAT }} -m 'build: version bump to %s'"
